name: CD # Continuous Deployment test

permissions:
  # TODO: once `releases: write` is supported, use it instead.
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'stellar-registry-cli-v[0-9]+.[0-9]+.[0-9]+*'
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    if: github.repository_owner == 'blaineheffron'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-pc-windows-msvc
            os: windows-2022
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-apple-darwin
            os: macos-12
          - target: x86_64-pc-windows-msvc
            os: windows-2022
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-12
          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04
          - target: universal-apple-darwin
            os: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu') && !contains(matrix.target, '-musl')
      - uses: taiki-e/install-action@cross
        if: contains(matrix.target, '-musl')
      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')
      - name: Set up OpenSSL for MUSL
        if: contains(matrix.target, '-musl')
        run: |
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: stellar-registry
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          archive: $tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OPENSSL_STATIC: ${{ env.OPENSSL_STATIC }}
